package com.softtek.mdm.dao;

import java.util.List;

import com.softtek.mdm.model.AndroidDeviceUsers;
import com.softtek.mdm.model.AndroidDeviceVirtualGroup;
import com.softtek.mdm.model.CollectVirtualModel;
import com.softtek.mdm.util.DataGridModel;

public interface AndroidDeviceVirtualGroupDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table android_device_virtual_group
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table android_device_virtual_group
     *
     * @mbggenerated
     */
    int insert(AndroidDeviceVirtualGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table android_device_virtual_group
     *
     * @mbggenerated
     */
    int insertSelective(AndroidDeviceVirtualGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table android_device_virtual_group
     *
     * @mbggenerated
     */
    AndroidDeviceVirtualGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table android_device_virtual_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AndroidDeviceVirtualGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table android_device_virtual_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AndroidDeviceVirtualGroup record);
    
    /**
     * 返回虚拟集合和虚拟组
     * @param orgId
     * @return
     */
    List<CollectVirtualModel> selectVirtualList(Integer orgId);
    
    /**
     * 批量插入Android设备策略授权虚拟组关联表
     * @param list
     * @return
     */
    int insertBatchPolicyVirtualGroup(List<AndroidDeviceVirtualGroup> list);
    
    /**
     * 根据虚拟组id获取所在的用户List
     * @param list
     * @return
     */
    List<AndroidDeviceUsers> selectVirtualUserList(DataGridModel params);
    
    /**
     * 根据虚拟组id获取所在的用户id
     * @param list
     * @return
     */
    List<Integer> selectVirtualUserIds(DataGridModel params);
    
    
    /**
     * 根据策略id获取关联的虚拟组
     * @param id
     * @return
     */
    List<AndroidDeviceVirtualGroup> selectVirtualGroupById(Integer id);
    
    /**
     * 根据策略id删除关联的虚拟组id
     * @param id
     * @return
     */
    int updateByVirtualGroupId(Integer id);
    
    /**
     * 根据策略id获取虚拟组
     * @param id
     * @return
     */
    List<Integer> selectVirtualById(Integer id);
    
    /**
     * 根据虚拟组id获取策略
     * @param params
     * @return
     */
    List<AndroidDeviceVirtualGroup> selectPolicyIdByVirtualId(DataGridModel params);
    
    /**
     * 根据策略idlist和虚拟组获取对应的用户策略
     * @param list
     * @return
     */
    List<AndroidDeviceUsers> selectVirtualByPolicyList(List<Integer> list);
    
}