package com.softtek.mdm.dao;

import java.util.List;

import com.softtek.mdm.model.AndroidPolicyList;
import com.softtek.mdm.model.NetBehaviorBlackWhiteList;
import com.softtek.mdm.util.DataGridModel;

public interface AndroidPolicyListDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table android_policy_list
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table android_policy_list
     *
     * @mbggenerated
     */
    int insert(AndroidPolicyList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table android_policy_list
     *
     * @mbggenerated
     */
    int insertSelective(AndroidPolicyList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table android_policy_list
     *
     * @mbggenerated
     */
    AndroidPolicyList selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table android_policy_list
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AndroidPolicyList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table android_policy_list
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AndroidPolicyList record);
    
    /**
     * 批量插入Android策略名单表 
     * @param list
     * @return
     */
    int insertBatchPolicyList(List<AndroidPolicyList> list);
    
    /**
     * 根据策略id删除关联的名单id
     * @param id
     * @return
     */
    int updateByNamelistId(Integer id);
    
    /**
     * 根据策略id获取黑白名单
     * @param id
     * @return
     */
    List<NetBehaviorBlackWhiteList> selectNameListByPolicyId(Integer id);
    
    /**
     * 根据黑白名单id获取策略id
     * @param params
     * @return
     */
    List<Integer> selectPolicyidListByBWID(DataGridModel params);
}