package com.softtek.mdm.dao;

import java.util.List;

import com.softtek.mdm.model.AndroidDeviceDepartment;
import com.softtek.mdm.model.AndroidDeviceUsers;
import com.softtek.mdm.util.DataGridModel;

public interface AndroidDeviceDepartmentDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table android_device_department
     *
     * @mbggenerated
     */ 
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table android_device_department
     *
     * @mbggenerated
     */
    int insert(AndroidDeviceDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table android_device_department
     *
     * @mbggenerated
     */
    int insertSelective(AndroidDeviceDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table android_device_department
     *
     * @mbggenerated
     */
    AndroidDeviceDepartment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table android_device_department
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AndroidDeviceDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table android_device_department
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AndroidDeviceDepartment record);
    
    /**
     * Android设备策略授权部门关联表
     * @param list
     * @return
     */
    int insertBatchDeviceDepartment(List<AndroidDeviceDepartment> list);
    
    /**
     * 根据部门id获取用户id
     * @param list
     * @return
     */
    List<AndroidDeviceUsers> selectDepartUserList(DataGridModel params);
    
    /**
     * 根据部门id获取用户id
     * @param list
     * @return
     */
    List<Integer> selectDepartUserIds(DataGridModel params);
    
    /**
     * 根据策略id获取对应的部门
     * @param id
     * @return
     */
    List<AndroidDeviceDepartment> selectDeviceDepartmentById(Integer id);
    
    /**
     * 根据策略id删除关联的部门id
     * @param id
     * @return
     */
    int updateByDepartId(Integer id);
    
    /**
     * 根据策略id获取部门id
     * @param id
     * @return
     */
    List<Integer> selectDepartmentById(Integer id);
    
    /**
     * 根据部门id获取关联的策略
     * @param params
     * @return
     */
    List<AndroidDeviceDepartment> selectPolicyByDepartId(DataGridModel params);
    
    /**
     * 根据策略ids和部门获取对应的用户id
     * @param list
     * @return
     */
    List<AndroidDeviceUsers> selectdepartIdsByPolicyList(List<Integer> list);
}