package com.softtek.mdm.dao;

import java.util.Collection;
import java.util.List;
import java.util.Map;

import com.softtek.mdm.model.AndroidDevicePolicy;
import com.softtek.mdm.model.NetBehaviorBlackWhiteList;
import com.softtek.mdm.model.PolicyEntity;
import com.softtek.mdm.util.DataGridModel;

public interface AndroidDevicePolicyDao extends CrudMapper<AndroidDevicePolicy,Integer>{
	   /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table android_device_policy
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table android_device_policy
     *
     * @mbggenerated
     */
    int insert(AndroidDevicePolicy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table android_device_policy
     *
     * @mbggenerated
     */
    int insertSelective(AndroidDevicePolicy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table android_device_policy
     *
     * @mbggenerated
     */
    AndroidDevicePolicy selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table android_device_policy
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AndroidDevicePolicy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table android_device_policy
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AndroidDevicePolicy record);
    
    /**
     * 获取设备策略List
     */
    List<PolicyEntity> getDevicePolicyList(DataGridModel params);
    
    /**
     * 获取设备策略List
     */
    List<PolicyEntity> getDevicePolicyListByParams(Map<String, Object> map);
    
    /**
     * 获取设备策略Size
     */
    int getDevicePolicySize(DataGridModel params);
    
    /**
     * 获取设备策略Size
     */
    int getDevicePolicySizeByParams(Map<String, Object> map);
    
    /**
     * 根据策略名称获取策略
     * @param name
     * @return
     */
    Integer selectDevicePolicyByName(DataGridModel params);
    
    /**
     * 查询该机构下所有的策略
     * @param org_id
     * @return
     */
    Collection<AndroidDevicePolicy> findAll(Integer orgId);
   
    /**
     * 获取设备策略Size
     */
    int getDevicePolicyCount(Integer orgid);
    
    /**
     * 根据参数获取网页黑白名单列表
     * @param params
     * @return
     */
    List<NetBehaviorBlackWhiteList> selectNetNameList(DataGridModel params);
    
    /**
     * 根据参数获取网页黑白名单大小
     * @param params
     * @return
     */
    Integer selectNetNameSize(DataGridModel params); 
    
    /**
     * 根据orgId，策略名称获取相应的策略
     * @param map
     * @return
     */
    AndroidDevicePolicy findPolicyByMap(Map<String, Object> map);

    /**
     * 获取该机构下的所有android策略
     * @param maps
     * @return
     */
	List<AndroidDevicePolicy> findAllByMap(Map<String, Object> maps);
}