package com.softtek.mdm.dao;

import java.util.List;

import com.softtek.mdm.model.ApplicationNameList;

public interface ApplicationNameListDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_name_list
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_name_list
     *
     * @mbggenerated
     */
    int insert(ApplicationNameList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_name_list
     *
     * @mbggenerated
     */
    int insertSelective(ApplicationNameList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_name_list
     *
     * @mbggenerated
     */
    ApplicationNameList selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_name_list
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ApplicationNameList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_name_list
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ApplicationNameList record);
    
    /**
     * 根据NameListId查找AppIds
     * @param id
     * @return
     */
    List<Integer> findAppIdsByNameListId(Integer id);
}