package com.softtek.mdm.dao;

import java.util.Collection;
import java.util.List;
import java.util.Map;

import com.softtek.mdm.model.AppList;
import com.softtek.mdm.model.ApplicationNameList;
import com.softtek.mdm.model.NameList;
import com.softtek.mdm.util.DataGridModel;

public interface NameListDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table name_list
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table name_list
     *
     * @mbggenerated
     */
    int insert(NameList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table name_list
     *
     * @mbggenerated
     */
    int insertSelective(NameList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table name_list
     *
     * @mbggenerated
     */
    NameList selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table name_list
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(NameList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table name_list
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(NameList record);
    
    /**
     * 获取名单列表
     * @return
     */
    List<NameList> selectNameList(DataGridModel params);
    
    /**
     * 获取名单大小
     * @return
     */
    int selectNameSize(DataGridModel params);
    
    /**
     * 根据类型1 黑名单  0 是白名单查询黑白名单信息
     * @param map
     * @return
     */
    Collection<NameList> findListByType(Map<String, Integer> map);
    
    /**
     * 删除应用
     * @return
     */
    int updateAppListByNameId(Integer id);
    
    /**
     * 删除应用名单关联表
     * @return
     */
    int updateAppNameListByNameId(Integer id);
    
    /**
     * 批量插入应用名单关联表
     * @param list
     * @return
     */
    int insertBatchAppNameList(List<ApplicationNameList> list);
    
    /**
     * 批量插入应用
     * @return
     */
    int insertBatchAppList(List<AppList> list); 
    
    /**
     * 根据名单id获取应用列表
     * @param id
     * @return
     */
    List<AppList> selectAppListByNameListId(Integer id);
    
    /**
     * 查询黑白名单是否存在
     * @param params
     * @return
     */
    Integer selectNameListById(DataGridModel params);
    
    /**
     * 根据名称和类型查找对应的记录
     * @param map
     * @return
     */
    Integer selectByName(Map<String, Object> map);
}