package com.softtek.mdm.dao;

import java.util.List;
import java.util.Map;

import com.softtek.mdm.model.SysmanageDeviceLog;

public interface SysmanageDeviceLogDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanage_device_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanage_device_log
     *
     * @mbggenerated
     */
    int insert(SysmanageDeviceLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanage_device_log
     *
     * @mbggenerated
     */
    int insertSelective(SysmanageDeviceLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanage_device_log
     *
     * @mbggenerated
     */
    SysmanageDeviceLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanage_device_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysmanageDeviceLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanage_device_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysmanageDeviceLog record);
    
	List<String> getAllDeviceLogType();

	Integer queryAllCountByParams(Map<String, Object> paramMap);
	
	List<SysmanageDeviceLog> queryDeviceLogList(Map<String, Object> paramMap);
	
	public List<SysmanageDeviceLog> queryDeviceLog(Map<String,Object> map);
	
	public int queryDeviceLogCount(Integer orgId);
	
	public String queryLogIsExite(Integer deviceId);
	
	List<SysmanageDeviceLog> findRecordsByMap(Map<String,Object> map);
	
	int findRecordsCountByDeviceId(Integer did);

	/**
	 * 查询设备日志记录数
	 *
	 * @author brave.chen
	 * @param map 参数map
	 * @return 数量
	 */
	int queryDeviceLogCountByParams(Map<String, Object> map);
	
	void deleteSysmanagelogJob();
	
	void deleteDevicelogJob();
	
	void deleteSecurityLogJob();
	
	void deleteNetbehaviorlogJob();
}