package com.f2b2c.eco.model.market;

import java.io.Serializable;
import java.util.Date;

/**
 * 收货地址表
 * 
 * @author jane.hui
 *
 */
public class CDeliveryAddressModel implements Serializable {

	/**
	 * 主键
	 * 
	 * @mbggenerated
	 */
	private Integer id;

	/**
	 * 收货人
	 * 
	 * @mbggenerated
	 */
	private String consignee;

	/**
	 * 区域外键
	 * 
	 * @mbggenerated
	 */
	private Integer areaId;

	/**
	 * 详细地址
	 * 
	 * @mbggenerated
	 */
	private String address;

	/**
	 * 详细地址（带省市区名字）
	 */
	private String fullAddress;
	
	/**
	 * 手机号
	 * 
	 * @mbggenerated
	 */
	private String mobile;

	/**
	 * 电话
	 * 
	 * @mbggenerated
	 */
	private String telephone;

	/**
	 * 邮箱
	 * 
	 * @mbggenerated
	 */
	private String email;

	/**
	 * 是否默认
	 * 
	 * @mbggenerated
	 */
	private String isDefault;

	/**
	 * 创建者
	 * 
	 * @mbggenerated
	 */
	private Integer createdUser;

	/**
	 * 创建时间
	 * 
	 * @mbggenerated
	 */
	private Date createdTime;

	/**
	 * 更新者
	 * 
	 * @mbggenerated
	 */
	private Integer updatedUser;

	/**
	 * 更新时间
	 * 
	 * @mbggenerated
	 */
	private Date updatedTime;

	/**
	 * 删除时间
	 * 
	 * @mbggenerated
	 */
	private Date deletedTime;

	private Integer userId;

	/**
	 * 删除状态标记位
	 */
	private Integer status;

	/**
	 * 经度
	 */
	private String longitude;
	/**
	 * 纬度
	 */
	private String latitude;

	/**
	 * 城市id
	 */
	private Integer cityId;
	/**
	 * 省份id
	 */
	private Integer provinceId;
	
	/**
	 * 区域名称
	 */
	private String areaName;
	
	/**
	 * 城市名称
	 */
	private String cityName;
	
	/**
	 * 省名称
	 */
	private String provinceName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table c_delivery_address
	 *
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getUserId() {
		return userId;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column c_delivery_address.consignee
	 *
	 * @return the value of c_delivery_address.consignee
	 *
	 * @mbggenerated
	 */
	public String getConsignee() {
		return consignee;
	}

	public void setConsignee(String consignee) {
		this.consignee = consignee == null ? null : consignee.trim();
	}

	public Integer getCityId() {
		return cityId;
	}

	public void setCityId(Integer cityId) {
		this.cityId = cityId;
	}

	public Integer getProvinceId() {
		return provinceId;
	}

	public void setProvinceId(Integer provinceId) {
		this.provinceId = provinceId;
	}

	public Integer getAreaId() {
		return areaId;
	}

	public void setAreaId(Integer areaId) {
		this.areaId = areaId;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address == null ? null : address.trim();
	}

	public String getMobile() {
		return mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile == null ? null : mobile.trim();
	}

	public String getTelephone() {
		return telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone == null ? null : telephone.trim();
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	public String getIsDefault() {
		return isDefault;
	}

	public void setIsDefault(String isDefault) {
		this.isDefault = isDefault == null ? null : isDefault.trim();
	}

	public Integer getCreatedUser() {
		return createdUser;
	}

	public void setCreatedUser(Integer createdUser) {
		this.createdUser = createdUser;
	}

	public Date getCreatedTime() {
		return createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	public Integer getUpdatedUser() {
		return updatedUser;
	}

	public void setUpdatedUser(Integer updatedUser) {
		this.updatedUser = updatedUser;
	}

	public Date getUpdatedTime() {
		return updatedTime;
	}

	public void setUpdatedTime(Date updatedTime) {
		this.updatedTime = updatedTime;
	}

	public Date getDeletedTime() {
		return deletedTime;
	}

	public void setDeletedTime(Date deletedTime) {
		this.deletedTime = deletedTime;
	}

	public String getLongitude() {
		return longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	public String getLatitude() {
		return latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	public String getAreaName() {
		return areaName;
	}

	public void setAreaName(String areaName) {
		this.areaName = areaName;
	}

	public String getCityName() {
		return cityName;
	}

	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

	public String getProvinceName() {
		return provinceName;
	}

	public void setProvinceName(String provinceName) {
		this.provinceName = provinceName;
	}
	
	public String getFullAddress() {
		return fullAddress;
	}

	public void setFullAddress(String fullAddress) {
		this.fullAddress = fullAddress;
	}

	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		CDeliveryAddressModel other = (CDeliveryAddressModel) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getConsignee() == null ? other.getConsignee() == null : this.getConsignee().equals(other.getConsignee()))
				&& (this.getAreaId() == null ? other.getAreaId() == null : this.getAreaId().equals(other.getAreaId()))
				&& (this.getAddress() == null ? other.getAddress() == null : this.getAddress().equals(other.getAddress()))
				&& (this.getMobile() == null ? other.getMobile() == null : this.getMobile().equals(other.getMobile()))
				&& (this.getTelephone() == null ? other.getTelephone() == null : this.getTelephone().equals(other.getTelephone()))
				&& (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
				&& (this.getIsDefault() == null ? other.getIsDefault() == null : this.getIsDefault().equals(other.getIsDefault()))
				&& (this.getCreatedUser() == null ? other.getCreatedUser() == null : this.getCreatedUser().equals(other.getCreatedUser()))
				&& (this.getCreatedTime() == null ? other.getCreatedTime() == null : this.getCreatedTime().equals(other.getCreatedTime()))
				&& (this.getUpdatedUser() == null ? other.getUpdatedUser() == null : this.getUpdatedUser().equals(other.getUpdatedUser()))
				&& (this.getUpdatedTime() == null ? other.getUpdatedTime() == null : this.getUpdatedTime().equals(other.getUpdatedTime()))
				&& (this.getLongitude() == null ? other.getLongitude() == null : this.getLongitude().equals(other.getLongitude()))
				&& (this.getLatitude() == null ? other.getLatitude() == null : this.getLatitude().equals(other.getLatitude()))
				&& (this.getDeletedTime() == null ? other.getDeletedTime() == null : this.getDeletedTime().equals(other.getDeletedTime()));
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getConsignee() == null) ? 0 : getConsignee().hashCode());
		result = prime * result + ((getAreaId() == null) ? 0 : getAreaId().hashCode());
		result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
		result = prime * result + ((getMobile() == null) ? 0 : getMobile().hashCode());
		result = prime * result + ((getTelephone() == null) ? 0 : getTelephone().hashCode());
		result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
		result = prime * result + ((getIsDefault() == null) ? 0 : getIsDefault().hashCode());
		result = prime * result + ((getCreatedUser() == null) ? 0 : getCreatedUser().hashCode());
		result = prime * result + ((getCreatedTime() == null) ? 0 : getCreatedTime().hashCode());
		result = prime * result + ((getUpdatedUser() == null) ? 0 : getUpdatedUser().hashCode());
		result = prime * result + ((getUpdatedTime() == null) ? 0 : getUpdatedTime().hashCode());
		result = prime * result + ((getLongitude() == null) ? 0 : getLongitude().hashCode());
		result = prime * result + ((getLatitude() == null) ? 0 : getLatitude().hashCode());
		result = prime * result + ((getDeletedTime() == null) ? 0 : getDeletedTime().hashCode());
		return result;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", consignee=").append(consignee);
		sb.append(", areaId=").append(areaId);
		sb.append(", address=").append(address);
		sb.append(", mobile=").append(mobile);
		sb.append(", telephone=").append(telephone);
		sb.append(", email=").append(email);
		sb.append(", isDefault=").append(isDefault);
		sb.append(", createdUser=").append(createdUser);
		sb.append(", createdTime=").append(createdTime);
		sb.append(", updatedUser=").append(updatedUser);
		sb.append(", updatedTime=").append(updatedTime);
		sb.append(", deletedTime=").append(deletedTime);
		sb.append(", latitude=").append(latitude);
		sb.append(", longitude=").append(longitude);
		sb.append("]");
		return sb.toString();
	}
}