package com.f2b2c.eco.dao.market;

import com.f2b2c.eco.model.market.BCityFreightModel;

/**
 * 
 * @author jane.hui
 *
 */
public interface BCityFreightDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_city_freight
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_city_freight
     *
     * @mbggenerated
     */
    int insert(BCityFreightModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_city_freight
     *
     * @mbggenerated
     */
    int insertSelective(BCityFreightModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_city_freight
     *
     * @mbggenerated
     */
    BCityFreightModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_city_freight
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BCityFreightModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_city_freight
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BCityFreightModel record);
}