package com.f2b2c.eco.dao.platform;

import java.util.List;
import java.util.Map;

import com.f2b2c.eco.model.platform.FAuthCodeModel;

public interface FAuthCodeDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_auth_code
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_auth_code
     *
     * @mbggenerated
     */
    int insert(FAuthCodeModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_auth_code
     *
     * @mbggenerated
     */
    int insertSelective(FAuthCodeModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_auth_code
     *
     * @mbggenerated
     */
    FAuthCodeModel selectByPrimaryKey(Integer id);
    
    List<FAuthCodeModel> findAllByFUserId(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_auth_code
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FAuthCodeModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_auth_code
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FAuthCodeModel record);
    
    int updateByCode(String code);

    /**
     * 分页查询
     * 
     * @return List<FUserModel>
     * @throws @author:
     *             ligang.yang@softtek.com
     * @version: 2016年9月10日 下午1:42:44
     */
    List<FAuthCodeModel> findWithPagination(Map<String, Object> paramMap);

    /**
     * 分页查询
     * 
     * @return int
     * @throws @author:
     *             ligang.yang@softtek.com
     * @version: 2016年9月10日 下午1:43:26
     */
    int queryCountByCondition(Map<String, Object> paramMap);
    /**
     * 通过authCode和userId去查询验证码是否存在
     * @param paramMap
     * @return
     */
	FAuthCodeModel getAuthCodeWithUserId(Map<Object, Object> paramMap);
	
	
	FAuthCodeModel queryCodeIsUser(String code);
	
}






