package com.softtek.mdm.model;

import java.io.Serializable;

public class ActionOperationDictionary implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_operation_dictionary.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_operation_dictionary.action_type
     *
     * @mbggenerated
     */
    private String actionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_operation_dictionary.action_name
     *
     * @mbggenerated
     */
    private String actionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table action_operation_dictionary
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_operation_dictionary.id
     *
     * @return the value of action_operation_dictionary.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_operation_dictionary.id
     *
     * @param id the value for action_operation_dictionary.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_operation_dictionary.action_type
     *
     * @return the value of action_operation_dictionary.action_type
     *
     * @mbggenerated
     */
    public String getActionType() {
        return actionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_operation_dictionary.action_type
     *
     * @param actionType the value for action_operation_dictionary.action_type
     *
     * @mbggenerated
     */
    public void setActionType(String actionType) {
        this.actionType = actionType == null ? null : actionType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_operation_dictionary.action_name
     *
     * @return the value of action_operation_dictionary.action_name
     *
     * @mbggenerated
     */
    public String getActionName() {
        return actionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_operation_dictionary.action_name
     *
     * @param actionName the value for action_operation_dictionary.action_name
     *
     * @mbggenerated
     */
    public void setActionName(String actionName) {
        this.actionName = actionName == null ? null : actionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_operation_dictionary
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ActionOperationDictionary other = (ActionOperationDictionary) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getActionType() == null ? other.getActionType() == null : this.getActionType().equals(other.getActionType()))
            && (this.getActionName() == null ? other.getActionName() == null : this.getActionName().equals(other.getActionName()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_operation_dictionary
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getActionType() == null) ? 0 : getActionType().hashCode());
        result = prime * result + ((getActionName() == null) ? 0 : getActionName().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_operation_dictionary
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", actionType=").append(actionType);
        sb.append(", actionName=").append(actionName);
        sb.append("]");
        return sb.toString();
    }
}