package com.softtek.mdm.model;

import java.io.Serializable;
import java.util.Date;

public class AndroidBlackList implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column android_black_list.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column android_black_list.android_device_policy_id
     *
     * @mbggenerated
     */
    private Integer androidDevicePolicyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column android_black_list.name_list_id
     *
     * @mbggenerated
     */
    private Integer nameListId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column android_black_list.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column android_black_list.create_user
     *
     * @mbggenerated
     */
    private Integer createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column android_black_list.update_date
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column android_black_list.update_user
     *
     * @mbggenerated
     */
    private Integer updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column android_black_list.delete_time
     *
     * @mbggenerated
     */
    private Date deleteTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table android_black_list
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column android_black_list.id
     *
     * @return the value of android_black_list.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column android_black_list.id
     *
     * @param id the value for android_black_list.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column android_black_list.android_device_policy_id
     *
     * @return the value of android_black_list.android_device_policy_id
     *
     * @mbggenerated
     */
    public Integer getAndroidDevicePolicyId() {
        return androidDevicePolicyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column android_black_list.android_device_policy_id
     *
     * @param androidDevicePolicyId the value for android_black_list.android_device_policy_id
     *
     * @mbggenerated
     */
    public void setAndroidDevicePolicyId(Integer androidDevicePolicyId) {
        this.androidDevicePolicyId = androidDevicePolicyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column android_black_list.name_list_id
     *
     * @return the value of android_black_list.name_list_id
     *
     * @mbggenerated
     */
    public Integer getNameListId() {
        return nameListId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column android_black_list.name_list_id
     *
     * @param nameListId the value for android_black_list.name_list_id
     *
     * @mbggenerated
     */
    public void setNameListId(Integer nameListId) {
        this.nameListId = nameListId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column android_black_list.create_date
     *
     * @return the value of android_black_list.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column android_black_list.create_date
     *
     * @param createDate the value for android_black_list.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column android_black_list.create_user
     *
     * @return the value of android_black_list.create_user
     *
     * @mbggenerated
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column android_black_list.create_user
     *
     * @param createUser the value for android_black_list.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column android_black_list.update_date
     *
     * @return the value of android_black_list.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column android_black_list.update_date
     *
     * @param updateDate the value for android_black_list.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column android_black_list.update_user
     *
     * @return the value of android_black_list.update_user
     *
     * @mbggenerated
     */
    public Integer getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column android_black_list.update_user
     *
     * @param updateUser the value for android_black_list.update_user
     *
     * @mbggenerated
     */
    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column android_black_list.delete_time
     *
     * @return the value of android_black_list.delete_time
     *
     * @mbggenerated
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column android_black_list.delete_time
     *
     * @param deleteTime the value for android_black_list.delete_time
     *
     * @mbggenerated
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table android_black_list
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AndroidBlackList other = (AndroidBlackList) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getAndroidDevicePolicyId() == null ? other.getAndroidDevicePolicyId() == null : this.getAndroidDevicePolicyId().equals(other.getAndroidDevicePolicyId()))
            && (this.getNameListId() == null ? other.getNameListId() == null : this.getNameListId().equals(other.getNameListId()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()))
            && (this.getUpdateUser() == null ? other.getUpdateUser() == null : this.getUpdateUser().equals(other.getUpdateUser()))
            && (this.getDeleteTime() == null ? other.getDeleteTime() == null : this.getDeleteTime().equals(other.getDeleteTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table android_black_list
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getAndroidDevicePolicyId() == null) ? 0 : getAndroidDevicePolicyId().hashCode());
        result = prime * result + ((getNameListId() == null) ? 0 : getNameListId().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        result = prime * result + ((getUpdateUser() == null) ? 0 : getUpdateUser().hashCode());
        result = prime * result + ((getDeleteTime() == null) ? 0 : getDeleteTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table android_black_list
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", androidDevicePolicyId=").append(androidDevicePolicyId);
        sb.append(", nameListId=").append(nameListId);
        sb.append(", createDate=").append(createDate);
        sb.append(", createUser=").append(createUser);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", deleteTime=").append(deleteTime);
        sb.append("]");
        return sb.toString();
    }
}