package com.softtek.mdm.model;

import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

public class AndroidDevicePolicy implements Serializable {
	
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column android_device_policy.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * 策略名称
     *
     * @mbggenerated
     */
    private String name;

    /**
     * 描述
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column android_device_policy.is_enable
     *
     * @mbggenerated
     */
    private String isEnable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column android_device_policy.org_id
     *
     * @mbggenerated
     */
    private Integer orgId;

    /**
     * 密码长度(第一个是存数据库的key，第二个是页面显示字段)
     * 0:4、1:5、2:6、3:7、4:8、5:9、6:10
     * @mbggenerated
     */
    private String passwordLength;

    /**
     * 密码复杂度要求
     * 0:数字密码 、1:数字+字母、 2:复杂密码
     *
     * @mbggenerated
     */
    private String passwordComplexity;

    /**
     * 自动锁定前最长时间
     * 0:永不 、1:15秒、2:30秒、3:1分钟、4:2分钟、5:5分钟、6:30分钟
     *
     * @mbggenerated
     */
    private String lockLongestTime;

    /**
     * 密码有效期
     * 0:永远、1:一周、2:两周、3:一个月、4:两个月、5:三个月
     *
     * @mbggenerated
     */
    private String passwordValidity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column android_device_policy.password_history
     *
     * @mbggenerated
     */
    private String passwordHistory;

    /**
     * 最大尝试次数(第一个存数据库的key，第二个是页面显示字段)
     * 0:无限制、1:4、2:5、3:6、4:7、5:8、6:9、7:10、8:11、9:12
     *
     * @mbggenerated
     */
    private String attemptTimes;

    /**
     * 设备加密
     * 1：是 0：否
     *
     * @mbggenerated
     */
    private String deviceEncryption;

    /**
     * 检测SD卡并报警
     * 1：是  0：否
     *
     * @mbggenerated
     */
    private String sdEncryption;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column android_device_policy.allow_use_sdcard
     *
     * @mbggenerated
     */
    private String allowUseSdcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column android_device_policy.allow_write_sdcard
     *
     * @mbggenerated
     */
    private String allowWriteSdcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column android_device_policy.allow_screenshots
     *
     * @mbggenerated
     */
    private String allowScreenshots;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column android_device_policy.allow_shear_plate
     *
     * @mbggenerated
     */
    private String allowShearPlate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column android_device_policy.visible_password
     *
     * @mbggenerated
     */
    private String visiblePassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column android_device_policy.allow_use_debugging
     *
     * @mbggenerated
     */
    private String allowUseDebugging;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column android_device_policy.allow_restore_factory_settings
     *
     * @mbggenerated
     */
    private String allowRestoreFactorySettings;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column android_device_policy.allow_ota_update
     *
     * @mbggenerated
     */
    private String allowOtaUpdate;

    /**
     * 允许使用相机
     * 1.是 0.否
     *
     * @mbggenerated
     */
    private String allowUseCamera;

    /**
     * 允许使用wifi
     * 1.是 0.否
     *
     * @mbggenerated
     */
    private String allowUseWifi;

    /**
     * 允许使用蓝牙
     * 1.是 0.否
     *
     * @mbggenerated
     */
    private String allowUseBluetooth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column android_device_policy.allow_usb_palyer
     *
     * @mbggenerated
     */
    private String allowUsbPalyer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column android_device_policy.synchronous_network_time
     *
     * @mbggenerated
     */
    private String synchronousNetworkTime;

    /**
     * 
     * 允许麦克风
     * 1.是 0.否
     * @mbggenerated
     */
    private String allowMicrophone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column android_device_policy.allow_nfc_communication
     *
     * @mbggenerated
     */
    private String allowNfcCommunication;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column android_device_policy.allow_mobile_data
     *
     * @mbggenerated
     */
    private String allowMobileData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column android_device_policy.allow_use_roam
     *
     * @mbggenerated
     */
    private String allowUseRoam;

    /**
     * 是否启用网页黑名单(网页)
     * 0.是 1.否
     *
     * @mbggenerated
     */
    private String enableBlacklist;

    /**
     * 是否启用应用黑白名单(应用)
     */
    private String enableAppNameList;
    
    /**
     * 是否限制上网时间
     * 1:是  0：否
     * @mbggenerated
     */
    private String isNetLimit;

    /**
     * 上网开始时间
     *
     * @mbggenerated
     */
    private String visitTimeStart;

    /**
     * 上网结束时间
     *
     * @mbggenerated
     */
    private String visitTimeEnd;
    
    /**
     * 上网时间段
     */
    private String visitTimeStr;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column android_device_policy.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column android_device_policy.create_user
     *
     * @mbggenerated
     */
    private Integer createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column android_device_policy.update_date
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column android_device_policy.update_user
     *
     * @mbggenerated
     */
    private Integer updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column android_device_policy.delete_time
     *
     * @mbggenerated
     */
    private Date deleteTime;

    /**
     * 名单列表Id
     */
    private String ids;
    
    /**
     * 名单列表名称
     */
    private String names;
    
    /**
     * 应用名单Id
     */
    private String appIds;
    
    /**
     * 应用名单名称Names
     */
    private String appNames;
    
    /**
     * 黑名单应用list
     */
    private List<AppList> appList;
    
    public String getIds() {
		return ids;
	}

	public void setIds(String ids) {
		this.ids = ids;
	}

	public String getNames() {
		return names;
	}

	public void setNames(String names) {
		this.names = names;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table android_device_policy
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

	/**
     * 推送极光推送的用户id列表(删除的情况)
     */
    private List<Integer> userIdList;
    
    /**
     * 部门List
     */
    private List<AndroidDeviceDepartment> list;
    
    /**
     * 用户List
     */
    private List<AndroidDeviceUsers> userList;
   
    /**
     * 虚拟组List
     */
    private List<AndroidDeviceVirtualGroup> virtualList;
    
    /**
     * 黑名单List
     */
    private List<BlackWhiteListUrl> urlList;
   
    /**
     * WIFI配置表
     */
    private List<WifiConfigure> wifiList;

    /**
     * 是否允许使用GPS(1.使用 0.禁用) 
     */
    private String allowUseGps;
    
	public List<WifiConfigure> getWifiList() {
		return wifiList;
	}

	public void setWifiList(List<WifiConfigure> wifiList) {
		this.wifiList = wifiList;
	}

	public List<BlackWhiteListUrl> getUrlList() {
		return urlList;
	}

	public void setUrlList(List<BlackWhiteListUrl> urlList) {
		this.urlList = urlList;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column android_device_policy.id
     *
     * @return the value of android_device_policy.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column android_device_policy.id
     *
     * @param id the value for android_device_policy.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column android_device_policy.name
     *
     * @return the value of android_device_policy.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column android_device_policy.name
     *
     * @param name the value for android_device_policy.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column android_device_policy.description
     *
     * @return the value of android_device_policy.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column android_device_policy.description
     *
     * @param description the value for android_device_policy.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column android_device_policy.is_enable
     *
     * @return the value of android_device_policy.is_enable
     *
     * @mbggenerated
     */
    public String getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column android_device_policy.is_enable
     *
     * @param isEnable the value for android_device_policy.is_enable
     *
     * @mbggenerated
     */
    public void setIsEnable(String isEnable) {
        this.isEnable = isEnable == null ? null : isEnable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column android_device_policy.org_id
     *
     * @return the value of android_device_policy.org_id
     *
     * @mbggenerated
     */
    public Integer getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column android_device_policy.org_id
     *
     * @param orgId the value for android_device_policy.org_id
     *
     * @mbggenerated
     */
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column android_device_policy.password_length
     *
     * @return the value of android_device_policy.password_length
     *
     * @mbggenerated
     */
    public String getPasswordLength() {
        return passwordLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column android_device_policy.password_length
     *
     * @param passwordLength the value for android_device_policy.password_length
     *
     * @mbggenerated
     */
    public void setPasswordLength(String passwordLength) {
        this.passwordLength = passwordLength == null ? null : passwordLength.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column android_device_policy.password_complexity
     *
     * @return the value of android_device_policy.password_complexity
     *
     * @mbggenerated
     */
    public String getPasswordComplexity() {
        return passwordComplexity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column android_device_policy.password_complexity
     *
     * @param passwordComplexity the value for android_device_policy.password_complexity
     *
     * @mbggenerated
     */
    public void setPasswordComplexity(String passwordComplexity) {
        this.passwordComplexity = passwordComplexity == null ? null : passwordComplexity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column android_device_policy.lock_longest_time
     *
     * @return the value of android_device_policy.lock_longest_time
     *
     * @mbggenerated
     */
    public String getLockLongestTime() {
        return lockLongestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column android_device_policy.lock_longest_time
     *
     * @param lockLongestTime the value for android_device_policy.lock_longest_time
     *
     * @mbggenerated
     */
    public void setLockLongestTime(String lockLongestTime) {
        this.lockLongestTime = lockLongestTime == null ? null : lockLongestTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column android_device_policy.password_validity
     *
     * @return the value of android_device_policy.password_validity
     *
     * @mbggenerated
     */
    public String getPasswordValidity() {
        return passwordValidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column android_device_policy.password_validity
     *
     * @param passwordValidity the value for android_device_policy.password_validity
     *
     * @mbggenerated
     */
    public void setPasswordValidity(String passwordValidity) {
        this.passwordValidity = passwordValidity == null ? null : passwordValidity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column android_device_policy.password_history
     *
     * @return the value of android_device_policy.password_history
     *
     * @mbggenerated
     */
    public String getPasswordHistory() {
        return passwordHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column android_device_policy.password_history
     *
     * @param passwordHistory the value for android_device_policy.password_history
     *
     * @mbggenerated
     */
    public void setPasswordHistory(String passwordHistory) {
        this.passwordHistory = passwordHistory == null ? null : passwordHistory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column android_device_policy.attempt_times
     *
     * @return the value of android_device_policy.attempt_times
     *
     * @mbggenerated
     */
    public String getAttemptTimes() {
        return attemptTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column android_device_policy.attempt_times
     *
     * @param attemptTimes the value for android_device_policy.attempt_times
     *
     * @mbggenerated
     */
    public void setAttemptTimes(String attemptTimes) {
        this.attemptTimes = attemptTimes == null ? null : attemptTimes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column android_device_policy.device_encryption
     *
     * @return the value of android_device_policy.device_encryption
     *
     * @mbggenerated
     */
    public String getDeviceEncryption() {
        return deviceEncryption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column android_device_policy.device_encryption
     *
     * @param deviceEncryption the value for android_device_policy.device_encryption
     *
     * @mbggenerated
     */
    public void setDeviceEncryption(String deviceEncryption) {
        this.deviceEncryption = deviceEncryption == null ? null : deviceEncryption.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column android_device_policy.sd_encryption
     *
     * @return the value of android_device_policy.sd_encryption
     *
     * @mbggenerated
     */
    public String getSdEncryption() {
        return sdEncryption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column android_device_policy.sd_encryption
     *
     * @param sdEncryption the value for android_device_policy.sd_encryption
     *
     * @mbggenerated
     */
    public void setSdEncryption(String sdEncryption) {
        this.sdEncryption = sdEncryption == null ? null : sdEncryption.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column android_device_policy.allow_use_sdcard
     *
     * @return the value of android_device_policy.allow_use_sdcard
     *
     * @mbggenerated
     */
    public String getAllowUseSdcard() {
        return allowUseSdcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column android_device_policy.allow_use_sdcard
     *
     * @param allowUseSdcard the value for android_device_policy.allow_use_sdcard
     *
     * @mbggenerated
     */
    public void setAllowUseSdcard(String allowUseSdcard) {
        this.allowUseSdcard = allowUseSdcard == null ? null : allowUseSdcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column android_device_policy.allow_write_sdcard
     *
     * @return the value of android_device_policy.allow_write_sdcard
     *
     * @mbggenerated
     */
    public String getAllowWriteSdcard() {
        return allowWriteSdcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column android_device_policy.allow_write_sdcard
     *
     * @param allowWriteSdcard the value for android_device_policy.allow_write_sdcard
     *
     * @mbggenerated
     */
    public void setAllowWriteSdcard(String allowWriteSdcard) {
        this.allowWriteSdcard = allowWriteSdcard == null ? null : allowWriteSdcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column android_device_policy.allow_screenshots
     *
     * @return the value of android_device_policy.allow_screenshots
     *
     * @mbggenerated
     */
    public String getAllowScreenshots() {
        return allowScreenshots;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column android_device_policy.allow_screenshots
     *
     * @param allowScreenshots the value for android_device_policy.allow_screenshots
     *
     * @mbggenerated
     */
    public void setAllowScreenshots(String allowScreenshots) {
        this.allowScreenshots = allowScreenshots == null ? null : allowScreenshots.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column android_device_policy.allow_shear_plate
     *
     * @return the value of android_device_policy.allow_shear_plate
     *
     * @mbggenerated
     */
    public String getAllowShearPlate() {
        return allowShearPlate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column android_device_policy.allow_shear_plate
     *
     * @param allowShearPlate the value for android_device_policy.allow_shear_plate
     *
     * @mbggenerated
     */
    public void setAllowShearPlate(String allowShearPlate) {
        this.allowShearPlate = allowShearPlate == null ? null : allowShearPlate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column android_device_policy.visible_password
     *
     * @return the value of android_device_policy.visible_password
     *
     * @mbggenerated
     */
    public String getVisiblePassword() {
        return visiblePassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column android_device_policy.visible_password
     *
     * @param visiblePassword the value for android_device_policy.visible_password
     *
     * @mbggenerated
     */
    public void setVisiblePassword(String visiblePassword) {
        this.visiblePassword = visiblePassword == null ? null : visiblePassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column android_device_policy.allow_use_debugging
     *
     * @return the value of android_device_policy.allow_use_debugging
     *
     * @mbggenerated
     */
    public String getAllowUseDebugging() {
        return allowUseDebugging;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column android_device_policy.allow_use_debugging
     *
     * @param allowUseDebugging the value for android_device_policy.allow_use_debugging
     *
     * @mbggenerated
     */
    public void setAllowUseDebugging(String allowUseDebugging) {
        this.allowUseDebugging = allowUseDebugging == null ? null : allowUseDebugging.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column android_device_policy.allow_restore_factory_settings
     *
     * @return the value of android_device_policy.allow_restore_factory_settings
     *
     * @mbggenerated
     */
    public String getAllowRestoreFactorySettings() {
        return allowRestoreFactorySettings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column android_device_policy.allow_restore_factory_settings
     *
     * @param allowRestoreFactorySettings the value for android_device_policy.allow_restore_factory_settings
     *
     * @mbggenerated
     */
    public void setAllowRestoreFactorySettings(String allowRestoreFactorySettings) {
        this.allowRestoreFactorySettings = allowRestoreFactorySettings == null ? null : allowRestoreFactorySettings.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column android_device_policy.allow_ota_update
     *
     * @return the value of android_device_policy.allow_ota_update
     *
     * @mbggenerated
     */
    public String getAllowOtaUpdate() {
        return allowOtaUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column android_device_policy.allow_ota_update
     *
     * @param allowOtaUpdate the value for android_device_policy.allow_ota_update
     *
     * @mbggenerated
     */
    public void setAllowOtaUpdate(String allowOtaUpdate) {
        this.allowOtaUpdate = allowOtaUpdate == null ? null : allowOtaUpdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column android_device_policy.allow_use _camera
     *
     * @return the value of android_device_policy.allow_use _camera
     *
     * @mbggenerated
     */
    public String getAllowUseCamera() {
        return allowUseCamera;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column android_device_policy.allow_use _camera
     *
     * @param allowUseCamera the value for android_device_policy.allow_use _camera
     *
     * @mbggenerated
     */
    public void setAllowUseCamera(String allowUseCamera) {
        this.allowUseCamera = allowUseCamera == null ? null : allowUseCamera.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column android_device_policy.allow_use_wifi
     *
     * @return the value of android_device_policy.allow_use_wifi
     *
     * @mbggenerated
     */
    public String getAllowUseWifi() {
        return allowUseWifi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column android_device_policy.allow_use_wifi
     *
     * @param allowUseWifi the value for android_device_policy.allow_use_wifi
     *
     * @mbggenerated
     */
    public void setAllowUseWifi(String allowUseWifi) {
        this.allowUseWifi = allowUseWifi == null ? null : allowUseWifi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column android_device_policy.allow_use_bluetooth
     *
     * @return the value of android_device_policy.allow_use_bluetooth
     *
     * @mbggenerated
     */
    public String getAllowUseBluetooth() {
        return allowUseBluetooth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column android_device_policy.allow_use_bluetooth
     *
     * @param allowUseBluetooth the value for android_device_policy.allow_use_bluetooth
     *
     * @mbggenerated
     */
    public void setAllowUseBluetooth(String allowUseBluetooth) {
        this.allowUseBluetooth = allowUseBluetooth == null ? null : allowUseBluetooth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column android_device_policy.allow_usb_palyer
     *
     * @return the value of android_device_policy.allow_usb_palyer
     *
     * @mbggenerated
     */
    public String getAllowUsbPalyer() {
        return allowUsbPalyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column android_device_policy.allow_usb_palyer
     *
     * @param allowUsbPalyer the value for android_device_policy.allow_usb_palyer
     *
     * @mbggenerated
     */
    public void setAllowUsbPalyer(String allowUsbPalyer) {
        this.allowUsbPalyer = allowUsbPalyer == null ? null : allowUsbPalyer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column android_device_policy.synchronous_network_time
     *
     * @return the value of android_device_policy.synchronous_network_time
     *
     * @mbggenerated
     */
    public String getSynchronousNetworkTime() {
        return synchronousNetworkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column android_device_policy.synchronous_network_time
     *
     * @param synchronousNetworkTime the value for android_device_policy.synchronous_network_time
     *
     * @mbggenerated
     */
    public void setSynchronousNetworkTime(String synchronousNetworkTime) {
        this.synchronousNetworkTime = synchronousNetworkTime == null ? null : synchronousNetworkTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column android_device_policy.allow_microphone
     *
     * @return the value of android_device_policy.allow_microphone
     *
     * @mbggenerated
     */
    public String getAllowMicrophone() {
        return allowMicrophone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column android_device_policy.allow_microphone
     *
     * @param allowMicrophone the value for android_device_policy.allow_microphone
     *
     * @mbggenerated
     */
    public void setAllowMicrophone(String allowMicrophone) {
        this.allowMicrophone = allowMicrophone == null ? null : allowMicrophone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column android_device_policy.allow_nfc_communication
     *
     * @return the value of android_device_policy.allow_nfc_communication
     *
     * @mbggenerated
     */
    public String getAllowNfcCommunication() {
        return allowNfcCommunication;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column android_device_policy.allow_nfc_communication
     *
     * @param allowNfcCommunication the value for android_device_policy.allow_nfc_communication
     *
     * @mbggenerated
     */
    public void setAllowNfcCommunication(String allowNfcCommunication) {
        this.allowNfcCommunication = allowNfcCommunication == null ? null : allowNfcCommunication.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column android_device_policy.allow_mobile_data
     *
     * @return the value of android_device_policy.allow_mobile_data
     *
     * @mbggenerated
     */
    public String getAllowMobileData() {
        return allowMobileData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column android_device_policy.allow_mobile_data
     *
     * @param allowMobileData the value for android_device_policy.allow_mobile_data
     *
     * @mbggenerated
     */
    public void setAllowMobileData(String allowMobileData) {
        this.allowMobileData = allowMobileData == null ? null : allowMobileData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column android_device_policy.allow_use_roam
     *
     * @return the value of android_device_policy.allow_use_roam
     *
     * @mbggenerated
     */
    public String getAllowUseRoam() {
        return allowUseRoam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column android_device_policy.allow_use_roam
     *
     * @param allowUseRoam the value for android_device_policy.allow_use_roam
     *
     * @mbggenerated
     */
    public void setAllowUseRoam(String allowUseRoam) {
        this.allowUseRoam = allowUseRoam == null ? null : allowUseRoam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column android_device_policy.enable _blacklist
     *
     * @return the value of android_device_policy.enable _blacklist
     *
     * @mbggenerated
     */
    public String getEnableBlacklist() {
        return enableBlacklist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column android_device_policy.enable _blacklist
     *
     * @param enableBlacklist the value for android_device_policy.enable _blacklist
     *
     * @mbggenerated
     */
    public void setEnableBlacklist(String enableBlacklist) {
        this.enableBlacklist = enableBlacklist == null ? null : enableBlacklist.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column android_device_policy.create_date
     *
     * @return the value of android_device_policy.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column android_device_policy.create_date
     *
     * @param createDate the value for android_device_policy.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column android_device_policy.create_user
     *
     * @return the value of android_device_policy.create_user
     *
     * @mbggenerated
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column android_device_policy.create_user
     *
     * @param createUser the value for android_device_policy.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column android_device_policy.update_date
     *
     * @return the value of android_device_policy.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column android_device_policy.update_date
     *
     * @param updateDate the value for android_device_policy.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column android_device_policy.update_user
     *
     * @return the value of android_device_policy.update_user
     *
     * @mbggenerated
     */
    public Integer getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column android_device_policy.update_user
     *
     * @param updateUser the value for android_device_policy.update_user
     *
     * @mbggenerated
     */
    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column android_device_policy.delete_time
     *
     * @return the value of android_device_policy.delete_time
     *
     * @mbggenerated
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column android_device_policy.delete_time
     *
     * @param deleteTime the value for android_device_policy.delete_time
     *
     * @mbggenerated
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }
    
    public List<AndroidDeviceDepartment> getList() {
		return list;
	}

	public void setList(List<AndroidDeviceDepartment> list) {
		this.list = list;
	}

	public List<AndroidDeviceUsers> getUserList() {
		return userList;
	}

	public void setUserList(List<AndroidDeviceUsers> userList) {
		this.userList = userList;
	}

	public List<AndroidDeviceVirtualGroup> getVirtualList() {
		return virtualList;
	}

	public void setVirtualList(List<AndroidDeviceVirtualGroup> virtualList) {
		this.virtualList = virtualList;
	}

	public String getIsNetLimit() {
		return isNetLimit;
	}

	public void setIsNetLimit(String isNetLimit) {
		this.isNetLimit = isNetLimit;
	}

	public String getVisitTimeStart() {
		return visitTimeStart;
	}

	public void setVisitTimeStart(String visitTimeStart) {
		this.visitTimeStart = visitTimeStart;
	}

	public String getVisitTimeEnd() {
		return visitTimeEnd;
	}

	public void setVisitTimeEnd(String visitTimeEnd) {
		this.visitTimeEnd = visitTimeEnd;
	}

	public String getEnableAppNameList() {
		return enableAppNameList;
	}

	public void setEnableAppNameList(String enableAppNameList) {
		this.enableAppNameList = enableAppNameList;
	}

	public String getAppIds() {
		return appIds;
	}

	public void setAppIds(String appIds) {
		this.appIds = appIds;
	}

	public String getAppNames() {
		return appNames;
	}

	public void setAppNames(String appNames) {
		this.appNames = appNames;
	}

	public List<AppList> getAppList() {
		return appList;
	}

	public void setAppList(List<AppList> appList) {
		this.appList = appList;
	}

	public String getVisitTimeStr() {
		return visitTimeStr;
	}

	public void setVisitTimeStr(String visitTimeStr) {
		this.visitTimeStr = visitTimeStr;
	}
	
	public String getAllowUseGps() {
		return allowUseGps;
	}

	public void setAllowUseGps(String allowUseGps) {
		this.allowUseGps = allowUseGps;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table android_device_policy
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AndroidDevicePolicy other = (AndroidDevicePolicy) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getIsEnable() == null ? other.getIsEnable() == null : this.getIsEnable().equals(other.getIsEnable()))
            && (this.getOrgId() == null ? other.getOrgId() == null : this.getOrgId().equals(other.getOrgId()))
            && (this.getPasswordLength() == null ? other.getPasswordLength() == null : this.getPasswordLength().equals(other.getPasswordLength()))
            && (this.getPasswordComplexity() == null ? other.getPasswordComplexity() == null : this.getPasswordComplexity().equals(other.getPasswordComplexity()))
            && (this.getLockLongestTime() == null ? other.getLockLongestTime() == null : this.getLockLongestTime().equals(other.getLockLongestTime()))
            && (this.getPasswordValidity() == null ? other.getPasswordValidity() == null : this.getPasswordValidity().equals(other.getPasswordValidity()))
            && (this.getPasswordHistory() == null ? other.getPasswordHistory() == null : this.getPasswordHistory().equals(other.getPasswordHistory()))
            && (this.getAttemptTimes() == null ? other.getAttemptTimes() == null : this.getAttemptTimes().equals(other.getAttemptTimes()))
            && (this.getDeviceEncryption() == null ? other.getDeviceEncryption() == null : this.getDeviceEncryption().equals(other.getDeviceEncryption()))
            && (this.getSdEncryption() == null ? other.getSdEncryption() == null : this.getSdEncryption().equals(other.getSdEncryption()))
            && (this.getAllowUseSdcard() == null ? other.getAllowUseSdcard() == null : this.getAllowUseSdcard().equals(other.getAllowUseSdcard()))
            && (this.getAllowWriteSdcard() == null ? other.getAllowWriteSdcard() == null : this.getAllowWriteSdcard().equals(other.getAllowWriteSdcard()))
            && (this.getAllowScreenshots() == null ? other.getAllowScreenshots() == null : this.getAllowScreenshots().equals(other.getAllowScreenshots()))
            && (this.getAllowShearPlate() == null ? other.getAllowShearPlate() == null : this.getAllowShearPlate().equals(other.getAllowShearPlate()))
            && (this.getVisiblePassword() == null ? other.getVisiblePassword() == null : this.getVisiblePassword().equals(other.getVisiblePassword()))
            && (this.getAllowUseDebugging() == null ? other.getAllowUseDebugging() == null : this.getAllowUseDebugging().equals(other.getAllowUseDebugging()))
            && (this.getAllowRestoreFactorySettings() == null ? other.getAllowRestoreFactorySettings() == null : this.getAllowRestoreFactorySettings().equals(other.getAllowRestoreFactorySettings()))
            && (this.getAllowOtaUpdate() == null ? other.getAllowOtaUpdate() == null : this.getAllowOtaUpdate().equals(other.getAllowOtaUpdate()))
            && (this.getAllowUseCamera() == null ? other.getAllowUseCamera() == null : this.getAllowUseCamera().equals(other.getAllowUseCamera()))
            && (this.getAllowUseWifi() == null ? other.getAllowUseWifi() == null : this.getAllowUseWifi().equals(other.getAllowUseWifi()))
            && (this.getAllowUseBluetooth() == null ? other.getAllowUseBluetooth() == null : this.getAllowUseBluetooth().equals(other.getAllowUseBluetooth()))
            && (this.getAllowUsbPalyer() == null ? other.getAllowUsbPalyer() == null : this.getAllowUsbPalyer().equals(other.getAllowUsbPalyer()))
            && (this.getSynchronousNetworkTime() == null ? other.getSynchronousNetworkTime() == null : this.getSynchronousNetworkTime().equals(other.getSynchronousNetworkTime()))
            && (this.getAllowMicrophone() == null ? other.getAllowMicrophone() == null : this.getAllowMicrophone().equals(other.getAllowMicrophone()))
            && (this.getAllowNfcCommunication() == null ? other.getAllowNfcCommunication() == null : this.getAllowNfcCommunication().equals(other.getAllowNfcCommunication()))
            && (this.getAllowMobileData() == null ? other.getAllowMobileData() == null : this.getAllowMobileData().equals(other.getAllowMobileData()))
            && (this.getAllowUseRoam() == null ? other.getAllowUseRoam() == null : this.getAllowUseRoam().equals(other.getAllowUseRoam()))
            && (this.getEnableBlacklist() == null ? other.getEnableBlacklist() == null : this.getEnableBlacklist().equals(other.getEnableBlacklist()))
            && (this.getIsNetLimit() == null ? other.getIsNetLimit() == null : this.getIsNetLimit().equals(other.getIsNetLimit()))
            && (this.getVisitTimeStart() == null ? other.getVisitTimeStart() == null : this.getVisitTimeStart().equals(other.getVisitTimeStart()))
            && (this.getVisitTimeEnd() == null ? other.getVisitTimeEnd() == null : this.getVisitTimeEnd().equals(other.getVisitTimeEnd()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()))
            && (this.getUpdateUser() == null ? other.getUpdateUser() == null : this.getUpdateUser().equals(other.getUpdateUser()))
            && (this.getDeleteTime() == null ? other.getDeleteTime() == null : this.getDeleteTime().equals(other.getDeleteTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table android_device_policy
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getIsEnable() == null) ? 0 : getIsEnable().hashCode());
        result = prime * result + ((getOrgId() == null) ? 0 : getOrgId().hashCode());
        result = prime * result + ((getPasswordLength() == null) ? 0 : getPasswordLength().hashCode());
        result = prime * result + ((getPasswordComplexity() == null) ? 0 : getPasswordComplexity().hashCode());
        result = prime * result + ((getLockLongestTime() == null) ? 0 : getLockLongestTime().hashCode());
        result = prime * result + ((getPasswordValidity() == null) ? 0 : getPasswordValidity().hashCode());
        result = prime * result + ((getPasswordHistory() == null) ? 0 : getPasswordHistory().hashCode());
        result = prime * result + ((getAttemptTimes() == null) ? 0 : getAttemptTimes().hashCode());
        result = prime * result + ((getDeviceEncryption() == null) ? 0 : getDeviceEncryption().hashCode());
        result = prime * result + ((getSdEncryption() == null) ? 0 : getSdEncryption().hashCode());
        result = prime * result + ((getAllowUseSdcard() == null) ? 0 : getAllowUseSdcard().hashCode());
        result = prime * result + ((getAllowWriteSdcard() == null) ? 0 : getAllowWriteSdcard().hashCode());
        result = prime * result + ((getAllowScreenshots() == null) ? 0 : getAllowScreenshots().hashCode());
        result = prime * result + ((getAllowShearPlate() == null) ? 0 : getAllowShearPlate().hashCode());
        result = prime * result + ((getVisiblePassword() == null) ? 0 : getVisiblePassword().hashCode());
        result = prime * result + ((getAllowUseDebugging() == null) ? 0 : getAllowUseDebugging().hashCode());
        result = prime * result + ((getAllowRestoreFactorySettings() == null) ? 0 : getAllowRestoreFactorySettings().hashCode());
        result = prime * result + ((getAllowOtaUpdate() == null) ? 0 : getAllowOtaUpdate().hashCode());
        result = prime * result + ((getAllowUseCamera() == null) ? 0 : getAllowUseCamera().hashCode());
        result = prime * result + ((getAllowUseWifi() == null) ? 0 : getAllowUseWifi().hashCode());
        result = prime * result + ((getAllowUseBluetooth() == null) ? 0 : getAllowUseBluetooth().hashCode());
        result = prime * result + ((getAllowUsbPalyer() == null) ? 0 : getAllowUsbPalyer().hashCode());
        result = prime * result + ((getSynchronousNetworkTime() == null) ? 0 : getSynchronousNetworkTime().hashCode());
        result = prime * result + ((getAllowMicrophone() == null) ? 0 : getAllowMicrophone().hashCode());
        result = prime * result + ((getAllowNfcCommunication() == null) ? 0 : getAllowNfcCommunication().hashCode());
        result = prime * result + ((getAllowMobileData() == null) ? 0 : getAllowMobileData().hashCode());
        result = prime * result + ((getAllowUseRoam() == null) ? 0 : getAllowUseRoam().hashCode());
        result = prime * result + ((getEnableBlacklist() == null) ? 0 : getEnableBlacklist().hashCode());
        result = prime * result + ((getIsNetLimit() == null) ? 0 : getIsNetLimit().hashCode());
        result = prime * result + ((getVisitTimeStart() == null) ? 0 : getVisitTimeStart().hashCode());
        result = prime * result + ((getVisitTimeEnd() == null) ? 0 : getVisitTimeEnd().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        result = prime * result + ((getUpdateUser() == null) ? 0 : getUpdateUser().hashCode());
        result = prime * result + ((getDeleteTime() == null) ? 0 : getDeleteTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table android_device_policy
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", description=").append(description);
        sb.append(", isEnable=").append(isEnable);
        sb.append(", orgId=").append(orgId);
        sb.append(", passwordLength=").append(passwordLength);
        sb.append(", passwordComplexity=").append(passwordComplexity);
        sb.append(", lockLongestTime=").append(lockLongestTime);
        sb.append(", passwordValidity=").append(passwordValidity);
        sb.append(", passwordHistory=").append(passwordHistory);
        sb.append(", attemptTimes=").append(attemptTimes);
        sb.append(", deviceEncryption=").append(deviceEncryption);
        sb.append(", sdEncryption=").append(sdEncryption);
        sb.append(", allowUseSdcard=").append(allowUseSdcard);
        sb.append(", allowWriteSdcard=").append(allowWriteSdcard);
        sb.append(", allowScreenshots=").append(allowScreenshots);
        sb.append(", allowShearPlate=").append(allowShearPlate);
        sb.append(", visiblePassword=").append(visiblePassword);
        sb.append(", allowUseDebugging=").append(allowUseDebugging);
        sb.append(", allowRestoreFactorySettings=").append(allowRestoreFactorySettings);
        sb.append(", allowOtaUpdate=").append(allowOtaUpdate);
        sb.append(", allowUseCamera=").append(allowUseCamera);
        sb.append(", allowUseWifi=").append(allowUseWifi);
        sb.append(", allowUseGps=").append(allowUseGps);
        sb.append(", allowUseBluetooth=").append(allowUseBluetooth);
        sb.append(", allowUsbPalyer=").append(allowUsbPalyer);
        sb.append(", synchronousNetworkTime=").append(synchronousNetworkTime);
        sb.append(", allowMicrophone=").append(allowMicrophone);
        sb.append(", allowNfcCommunication=").append(allowNfcCommunication);
        sb.append(", allowMobileData=").append(allowMobileData);
        sb.append(", allowUseRoam=").append(allowUseRoam);
        sb.append(", enableBlacklist=").append(enableBlacklist);
        sb.append(", isNetLimit=").append(isNetLimit);
        sb.append(", visitTimeStart=").append(visitTimeStart);
        sb.append(", visitTimeEnd=").append(visitTimeEnd);
        sb.append(", createDate=").append(createDate);
        sb.append(", createUser=").append(createUser);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", deleteTime=").append(deleteTime);
        sb.append("]");
        return sb.toString();
    }

	// 创建时间
    @SuppressWarnings("unused")
	private String createDateStr;
    // 更新时间按
    @SuppressWarnings("unused")
	private String updateDateStr;
    
	public List<Integer> getUserIdList() {
		return userIdList;
	}

	public void setUserIdList(List<Integer> userIdList) {
		this.userIdList = userIdList;
	}

	public String getCreateDateStr() {
		if(getCreateDate() != null){
			SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
			return sdf.format(getCreateDate());
		}
		return "";
	}

	public void setCreateDateStr(String createDateStr) {
		this.createDateStr = createDateStr;
	}

	public String getUpdateDateStr() {
		if(getUpdateDate() != null){
			SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
			return sdf.format(getUpdateDate());
		}
		return "";
	}

	public void setUpdateDateStr(String updateDateStr) {
		this.updateDateStr = updateDateStr;
	}
}