package com.softtek.mdm.model;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

public class NameList implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column name_list.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column name_list.list_type
     *
     * @mbggenerated
     */
    private String listType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column name_list.list_name
     *
     * @mbggenerated
     */
    private String listName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column name_list.org_id
     *
     * @mbggenerated
     */
    private Integer orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column name_list.app_count
     *
     * @mbggenerated
     */
    private Integer appCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column name_list.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column name_list.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column name_list.create_user
     *
     * @mbggenerated
     */
    private Integer createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column name_list.update_date
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column name_list.update_user
     *
     * @mbggenerated
     */
    private Integer updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column name_list.delete_time
     *
     * @mbggenerated
     */
    private Date deleteTime;
    
    /**
     * 应用列表
     */
    private List<AppList> appList;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table name_list
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column name_list.id
     *
     * @return the value of name_list.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column name_list.id
     *
     * @param id the value for name_list.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column name_list.list_type
     *
     * @return the value of name_list.list_type
     *
     * @mbggenerated
     */
    public String getListType() {
        return listType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column name_list.list_type
     *
     * @param listType the value for name_list.list_type
     *
     * @mbggenerated
     */
    public void setListType(String listType) {
        this.listType = listType == null ? null : listType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column name_list.list_name
     *
     * @return the value of name_list.list_name
     *
     * @mbggenerated
     */
    public String getListName() {
        return listName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column name_list.list_name
     *
     * @param listName the value for name_list.list_name
     *
     * @mbggenerated
     */
    public void setListName(String listName) {
        this.listName = listName == null ? null : listName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column name_list.org_id
     *
     * @return the value of name_list.org_id
     *
     * @mbggenerated
     */
    public Integer getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column name_list.org_id
     *
     * @param orgId the value for name_list.org_id
     *
     * @mbggenerated
     */
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column name_list.app_count
     *
     * @return the value of name_list.app_count
     *
     * @mbggenerated
     */
    public Integer getAppCount() {
        return appCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column name_list.app_count
     *
     * @param appCount the value for name_list.app_count
     *
     * @mbggenerated
     */
    public void setAppCount(Integer appCount) {
        this.appCount = appCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column name_list.remark
     *
     * @return the value of name_list.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column name_list.remark
     *
     * @param remark the value for name_list.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column name_list.create_date
     *
     * @return the value of name_list.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column name_list.create_date
     *
     * @param createDate the value for name_list.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column name_list.create_user
     *
     * @return the value of name_list.create_user
     *
     * @mbggenerated
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column name_list.create_user
     *
     * @param createUser the value for name_list.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column name_list.update_date
     *
     * @return the value of name_list.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column name_list.update_date
     *
     * @param updateDate the value for name_list.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column name_list.update_user
     *
     * @return the value of name_list.update_user
     *
     * @mbggenerated
     */
    public Integer getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column name_list.update_user
     *
     * @param updateUser the value for name_list.update_user
     *
     * @mbggenerated
     */
    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column name_list.delete_time
     *
     * @return the value of name_list.delete_time
     *
     * @mbggenerated
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column name_list.delete_time
     *
     * @param deleteTime the value for name_list.delete_time
     *
     * @mbggenerated
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }
    
	public List<AppList> getAppList() {
		return appList;
	}

	public void setAppList(List<AppList> appList) {
		this.appList = appList;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table name_list
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        NameList other = (NameList) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getListType() == null ? other.getListType() == null : this.getListType().equals(other.getListType()))
            && (this.getListName() == null ? other.getListName() == null : this.getListName().equals(other.getListName()))
            && (this.getOrgId() == null ? other.getOrgId() == null : this.getOrgId().equals(other.getOrgId()))
            && (this.getAppCount() == null ? other.getAppCount() == null : this.getAppCount().equals(other.getAppCount()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()))
            && (this.getUpdateUser() == null ? other.getUpdateUser() == null : this.getUpdateUser().equals(other.getUpdateUser()))
            && (this.getDeleteTime() == null ? other.getDeleteTime() == null : this.getDeleteTime().equals(other.getDeleteTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table name_list
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getListType() == null) ? 0 : getListType().hashCode());
        result = prime * result + ((getListName() == null) ? 0 : getListName().hashCode());
        result = prime * result + ((getOrgId() == null) ? 0 : getOrgId().hashCode());
        result = prime * result + ((getAppCount() == null) ? 0 : getAppCount().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        result = prime * result + ((getUpdateUser() == null) ? 0 : getUpdateUser().hashCode());
        result = prime * result + ((getDeleteTime() == null) ? 0 : getDeleteTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table name_list
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", listType=").append(listType);
        sb.append(", listName=").append(listName);
        sb.append(", orgId=").append(orgId);
        sb.append(", appCount=").append(appCount);
        sb.append(", remark=").append(remark);
        sb.append(", createDate=").append(createDate);
        sb.append(", createUser=").append(createUser);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", deleteTime=").append(deleteTime);
        sb.append("]");
        return sb.toString();
    }
}