package com.softtek.mdm.model;

import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.Date;

public class SysmanageLog implements Serializable {
    /**
     * 编号
     * 
     * @mbggenerated
     */
    private Integer id;

    /**
     * 用户id
     * 
     * @mbggenerated
     */
    private Integer userId;
    
    /**
     * 机构id
     * 
     * @mbggenerated
     */
    private Integer orgId;

    /**
     * 用户类型
     * 
     * @mbggenerated
     */
    private String userType;

    /**
     * 操作类型
     * 
     * @mbggenerated
     */
    private String operateType;

    /**
     * 操作时间
     *
     * @mbggenerated
     */
    private Date operateTime;

    /**
     * 操作内容
     * 
     * @mbggenerated
     */
    private String operateContent;

    /**
     * 创建时间
     * 
     * @mbggenerated
     */
    private Date createDate;

    /**
     * 创建者
     *
     * @mbggenerated
     */
    private Integer createUser;

    /**
     * 更新时间
     * 
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * 更新者
     * 
     * @mbggenerated
     */
    private Integer updateUser;

    /**
     * 删除时间
     * 
     * @mbggenerated
     */
    private Date deleteTime;

    /**
     * 序列化
     * 
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 用户帐号
     */
    private String username;
    
    /**
     * 用户名称
     */
    private String name;

    /**
     * 机构名称
     */
    private String orgName;
    
    @SuppressWarnings("unused")
	private String operateTimeStr;
    
    public Integer getId() {
        return id;
    }

    /**
     * @return name
     */

    public String getName() {
        return name;
    }

    /**
     * @param name
     *            要设置的 name
     */

    public void setName(String name) {
        this.name = name;
    }

    /**
     * @return serialversionuid
     */

    public static long getSerialversionuid() {
        return serialVersionUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmanage_log.id
     *
     * @param id the value for sysmanage_log.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmanage_log.user_id
     *
     * @return the value of sysmanage_log.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmanage_log.user_id
     *
     * @param userId the value for sysmanage_log.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmanage_log.org_id
     *
     * @return the value of sysmanage_log.org_id
     *
     * @mbggenerated
     */
    public Integer getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmanage_log.org_id
     *
     * @param orgId the value for sysmanage_log.org_id
     *
     * @mbggenerated
     */
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmanage_log.user_type
     *
     * @return the value of sysmanage_log.user_type
     *
     * @mbggenerated
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmanage_log.user_type
     *
     * @param userType the value for sysmanage_log.user_type
     *
     * @mbggenerated
     */
    public void setUserType(String userType) {
        this.userType = userType == null ? null : userType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmanage_log.operate_type
     *
     * @return the value of sysmanage_log.operate_type
     *
     * @mbggenerated
     */
    public String getOperateType() {
        return operateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmanage_log.operate_type
     *
     * @param operateType the value for sysmanage_log.operate_type
     *
     * @mbggenerated
     */
    public void setOperateType(String operateType) {
        this.operateType = operateType == null ? null : operateType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmanage_log.operate_time
     *
     * @return the value of sysmanage_log.operate_time
     *
     * @mbggenerated
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmanage_log.operate_time
     *
     * @param operateTime the value for sysmanage_log.operate_time
     *
     * @mbggenerated
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmanage_log.operate_content
     *
     * @return the value of sysmanage_log.operate_content
     *
     * @mbggenerated
     */
    public String getOperateContent() {
        return operateContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmanage_log.operate_content
     *
     * @param operateContent the value for sysmanage_log.operate_content
     *
     * @mbggenerated
     */
    public void setOperateContent(String operateContent) {
        this.operateContent = operateContent == null ? null : operateContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmanage_log.create_date
     *
     * @return the value of sysmanage_log.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmanage_log.create_date
     *
     * @param createDate the value for sysmanage_log.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmanage_log.create_user
     *
     * @return the value of sysmanage_log.create_user
     *
     * @mbggenerated
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmanage_log.create_user
     *
     * @param createUser the value for sysmanage_log.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmanage_log.update_date
     *
     * @return the value of sysmanage_log.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmanage_log.update_date
     *
     * @param updateDate the value for sysmanage_log.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmanage_log.update_user
     *
     * @return the value of sysmanage_log.update_user
     *
     * @mbggenerated
     */
    public Integer getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmanage_log.update_user
     *
     * @param updateUser the value for sysmanage_log.update_user
     *
     * @mbggenerated
     */
    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmanage_log.delete_time
     *
     * @return the value of sysmanage_log.delete_time
     *
     * @mbggenerated
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmanage_log.delete_time
     *
     * @param deleteTime the value for sysmanage_log.delete_time
     *
     * @mbggenerated
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }
    
    public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getOrgName() {
		return orgName;
	}

	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}

	public String getOperateTimeStr() {
		if(getOperateTime() != null){
			SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
			return sdf.format(getOperateTime());
		}
		return null;
	}

	public void setOperateTimeStr(String operateTimeStr) {
		this.operateTimeStr = operateTimeStr;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanage_log
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SysmanageLog other = (SysmanageLog) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getOrgId() == null ? other.getOrgId() == null : this.getOrgId().equals(other.getOrgId()))
            && (this.getUserType() == null ? other.getUserType() == null : this.getUserType().equals(other.getUserType()))
            && (this.getOperateType() == null ? other.getOperateType() == null : this.getOperateType().equals(other.getOperateType()))
            && (this.getOperateTime() == null ? other.getOperateTime() == null : this.getOperateTime().equals(other.getOperateTime()))
            && (this.getOperateContent() == null ? other.getOperateContent() == null : this.getOperateContent().equals(other.getOperateContent()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()))
            && (this.getUpdateUser() == null ? other.getUpdateUser() == null : this.getUpdateUser().equals(other.getUpdateUser()))
            && (this.getDeleteTime() == null ? other.getDeleteTime() == null : this.getDeleteTime().equals(other.getDeleteTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanage_log
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getOrgId() == null) ? 0 : getOrgId().hashCode());
        result = prime * result + ((getUserType() == null) ? 0 : getUserType().hashCode());
        result = prime * result + ((getOperateType() == null) ? 0 : getOperateType().hashCode());
        result = prime * result + ((getOperateTime() == null) ? 0 : getOperateTime().hashCode());
        result = prime * result + ((getOperateContent() == null) ? 0 : getOperateContent().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        result = prime * result + ((getUpdateUser() == null) ? 0 : getUpdateUser().hashCode());
        result = prime * result + ((getDeleteTime() == null) ? 0 : getDeleteTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanage_log
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", orgId=").append(orgId);
        sb.append(", userType=").append(userType);
        sb.append(", operateType=").append(operateType);
        sb.append(", operateTime=").append(operateTime);
        sb.append(", operateContent=").append(operateContent);
        sb.append(", createDate=").append(createDate);
        sb.append(", createUser=").append(createUser);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", deleteTime=").append(deleteTime);
        sb.append("]");
        return sb.toString();
    }
}