package com.softtek.mdm.model;

import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.Date;

public class SysmanageDeviceLog implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmanage_device_log.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmanage_device_log.user_id
     *
     * @mbggenerated
     */
    private Integer userId;
    
    private UserModel usermodel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmanage_device_log.device_id
     *
     * @mbggenerated
     */
    private Integer deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmanage_device_log.org_id
     *
     * @mbggenerated
     */
    private Integer orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmanage_device_log.operate_date
     *
     * @mbggenerated
     */
    private Date operateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmanage_device_log.event_type
     *
     * @mbggenerated
     */
    private String eventType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmanage_device_log.operate_content
     *
     * @mbggenerated
     */
    private String operateContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmanage_device_log.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmanage_device_log.create_user
     *
     * @mbggenerated
     */
    private Integer createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmanage_device_log.update_date
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmanage_device_log.update_user
     *
     * @mbggenerated
     */
    private Integer updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmanage_device_log.delete_time
     *
     * @mbggenerated
     */
    private Date deleteTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sysmanage_device_log
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;
    
    private String deviceName;
    
    private String userName;
    
    private String realName;
    
    private String name;//所属机构
    
    private String operateTime;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmanage_device_log.id
     *
     * @return the value of sysmanage_device_log.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmanage_device_log.id
     *
     * @param id the value for sysmanage_device_log.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmanage_device_log.user_id
     *
     * @return the value of sysmanage_device_log.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmanage_device_log.user_id
     *
     * @param userId the value for sysmanage_device_log.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmanage_device_log.device_id
     *
     * @return the value of sysmanage_device_log.device_id
     *
     * @mbggenerated
     */
    public Integer getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmanage_device_log.device_id
     *
     * @param deviceId the value for sysmanage_device_log.device_id
     *
     * @mbggenerated
     */
    public void setDeviceId(Integer deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmanage_device_log.org_id
     *
     * @return the value of sysmanage_device_log.org_id
     *
     * @mbggenerated
     */
    public Integer getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmanage_device_log.org_id
     *
     * @param orgId the value for sysmanage_device_log.org_id
     *
     * @mbggenerated
     */
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmanage_device_log.operate_date
     *
     * @return the value of sysmanage_device_log.operate_date
     *
     * @mbggenerated
     */
    public Date getOperateDate() {
        return operateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmanage_device_log.operate_date
     *
     * @param operateDate the value for sysmanage_device_log.operate_date
     *
     * @mbggenerated
     */
    public void setOperateDate(Date operateDate) {
        this.operateDate = operateDate;
    }

	public String getEventType() {
		return eventType;
	}

	public void setEventType(String eventType) {
		this.eventType = eventType;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmanage_device_log.operate_content
     *
     * @return the value of sysmanage_device_log.operate_content
     *
     * @mbggenerated
     */
    public String getOperateContent() {
        return operateContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmanage_device_log.operate_content
     *
     * @param operateContent the value for sysmanage_device_log.operate_content
     *
     * @mbggenerated
     */
    public void setOperateContent(String operateContent) {
        this.operateContent = operateContent == null ? null : operateContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmanage_device_log.create_date
     *
     * @return the value of sysmanage_device_log.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmanage_device_log.create_date
     *
     * @param createDate the value for sysmanage_device_log.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmanage_device_log.create_user
     *
     * @return the value of sysmanage_device_log.create_user
     *
     * @mbggenerated
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmanage_device_log.create_user
     *
     * @param createUser the value for sysmanage_device_log.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmanage_device_log.update_date
     *
     * @return the value of sysmanage_device_log.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmanage_device_log.update_date
     *
     * @param updateDate the value for sysmanage_device_log.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmanage_device_log.update_user
     *
     * @return the value of sysmanage_device_log.update_user
     *
     * @mbggenerated
     */
    public Integer getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmanage_device_log.update_user
     *
     * @param updateUser the value for sysmanage_device_log.update_user
     *
     * @mbggenerated
     */
    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmanage_device_log.delete_time
     *
     * @return the value of sysmanage_device_log.delete_time
     *
     * @mbggenerated
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmanage_device_log.delete_time
     *
     * @param deleteTime the value for sysmanage_device_log.delete_time
     *
     * @mbggenerated
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }

    public String getDeviceName() {
		return deviceName;
	}

	public void setDeviceName(String deviceName) {
		this.deviceName = deviceName;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getRealName() {
		return realName;
	}

	public void setRealName(String realName) {
		this.realName = realName;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public UserModel getUsermodel() {
		return usermodel;
	}

	public void setUsermodel(UserModel usermodel) {
		this.usermodel = usermodel;
	}

	public String getOperateTime() {
		if(getOperateDate() != null){
			SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
			return sdf.format(getOperateDate());
		}
		return "";
	}

	public void setOperateTime(String operateTime) {
		this.operateTime = operateTime;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("SysmanageDeviceLog [id=");
		builder.append(id);
		builder.append(", userId=");
		builder.append(userId);
		builder.append(", usermodel=");
		builder.append(usermodel);
		builder.append(", deviceId=");
		builder.append(deviceId);
		builder.append(", orgId=");
		builder.append(orgId);
		builder.append(", operateDate=");
		builder.append(operateDate);
		builder.append(", eventType=");
		builder.append(eventType);
		builder.append(", operateContent=");
		builder.append(operateContent);
		builder.append(", createDate=");
		builder.append(createDate);
		builder.append(", createUser=");
		builder.append(createUser);
		builder.append(", updateDate=");
		builder.append(updateDate);
		builder.append(", updateUser=");
		builder.append(updateUser);
		builder.append(", deleteTime=");
		builder.append(deleteTime);
		builder.append(", deviceName=");
		builder.append(deviceName);
		builder.append(", userName=");
		builder.append(userName);
		builder.append(", realName=");
		builder.append(realName);
		builder.append(", name=");
		builder.append(name);
		builder.append(", operateTime=");
		builder.append(operateTime);
		builder.append("]");
		return builder.toString();
	}
	
	

}