package com.f2b2c.eco.model.platform;

import java.io.Serializable;
import java.util.Date;

public class FRoleModel implements Serializable {

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = -794763776703003726L;

	/**
	 * 角色ID
	 */
	private Integer id;

	/**
	 * 角色名称
	 */
	private String roleName;

	/**
	 * 创建人
	 */
	private FUserModel createdUser;

	/**
	 * 创建时间
	 */
	private Date createdTime;

	/**
	 * 更新人
	 */
	private FUserModel updatedUser;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column f_role.updated_time
	 *
	 * @mbggenerated
	 */
	private Date updatedTime;

	/**
	 * 更新时间
	 */
	private Date deletedTime;

	/**
	 * 删除时间
	 */
	private String remark;

	/**
	 * 角色类型
	 */
	private Integer roleType;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getRoleName() {
		return roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public FUserModel getCreatedUser() {
		return createdUser;
	}

	public void setCreatedUser(FUserModel createdUser) {
		this.createdUser = createdUser;
	}

	public Date getCreatedTime() {
		return createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	public FUserModel getUpdatedUser() {
		return updatedUser;
	}

	public void setUpdatedUser(FUserModel updatedUser) {
		this.updatedUser = updatedUser;
	}

	public Date getUpdatedTime() {
		return updatedTime;
	}

	public void setUpdatedTime(Date updatedTime) {
		this.updatedTime = updatedTime;
	}

	public Date getDeletedTime() {
		return deletedTime;
	}

	public void setDeletedTime(Date deletedTime) {
		this.deletedTime = deletedTime;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	public Integer getRoleType() {
		return roleType;
	}

	public void setRoleType(Integer roleType) {
		this.roleType = roleType;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("FRoleModel [id=");
		builder.append(id);
		builder.append(", roleName=");
		builder.append(roleName);
		builder.append(", createdUser=");
		builder.append(createdUser);
		builder.append(", createdTime=");
		builder.append(createdTime);
		builder.append(", updatedUser=");
		builder.append(updatedUser);
		builder.append(", updatedTime=");
		builder.append(updatedTime);
		builder.append(", deletedTime=");
		builder.append(deletedTime);
		builder.append(", remark=");
		builder.append(remark);
		builder.append(", roleType=");
		builder.append(roleType);
		builder.append("]");
		return builder.toString();
	}

}